[project]
name = "fiafcore-bundesarchiv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lxml==6.0.0",
    "pymongo==4.13.2",
    "python-dotenv==1.1.1",
    "rdflib==7.1.3",
    "tqdm==4.67.1",
]
